// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwagBackend.Data;
using SwagBackend.Models;

#nullable disable

namespace SwagBackend.Migrations
{
    [DbContext(typeof(SwagDbContext))]
    partial class SwagDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "media_type", "media_type", new[] { "image", "video" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "message_type", "message_type", new[] { "text", "image", "video" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_type", "notification_type", new[] { "maintenance_alert", "vendor_post", "insurance_expiry", "new_event", "mention", "nearby_suggestion", "system_alert", "account_status", "new_review", "new_follower", "event_update", "inventory_tip" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "otp_purpose", "otp_purpose", new[] { "signup", "forgot_password", "change_contact" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "post_type", "post_type", new[] { "post", "event" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", "user_role", new[] { "customer", "vendor", "admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vendor_status", "vendor_status", new[] { "pending", "active", "rejected" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SwagBackend.Models.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("SwagBackend.Models.CarMaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RecordDate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("record_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("car_maintenance_records");
                });

            modelBuilder.Entity("SwagBackend.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text")
                        .HasColumnName("media_url");

                    b.Property<string>("MessageText")
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<MessageType>("MessageType")
                        .HasColumnType("message_type")
                        .HasColumnName("message_type");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<UserRole>("SenderType")
                        .HasColumnType("user_role")
                        .HasColumnName("sender_type");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("chat_messages");
                });

            modelBuilder.Entity("SwagBackend.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_message");

                    b.Property<DateTime?>("LastMessageTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_time");

                    b.Property<int>("P1Unread")
                        .HasColumnType("integer")
                        .HasColumnName("p1_unread");

                    b.Property<int>("P2Unread")
                        .HasColumnType("integer")
                        .HasColumnName("p2_unread");

                    b.Property<Guid>("ParticipantOneId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_one_id");

                    b.Property<UserRole>("ParticipantOneType")
                        .HasColumnType("user_role")
                        .HasColumnName("participant_one_type");

                    b.Property<Guid>("ParticipantTwoId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_two_id");

                    b.Property<UserRole>("ParticipantTwoType")
                        .HasColumnType("user_role")
                        .HasColumnName("participant_two_type");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantOneId", "ParticipantOneType", "ParticipantTwoId", "ParticipantTwoType")
                        .IsUnique();

                    b.ToTable("conversations");
                });

            modelBuilder.Entity("SwagBackend.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BannerImage")
                        .HasColumnType("text")
                        .HasColumnName("banner_image");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("boolean")
                        .HasColumnName("dark_mode");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text")
                        .HasColumnName("profile_image");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("push_notifications");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("SwagBackend.Models.CustomerCar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<string>("CarImage")
                        .HasColumnType("text")
                        .HasColumnName("car_image");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentMileage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_mileage");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("EngineType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("engine_type");

                    b.Property<string>("FuelType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fuel_type");

                    b.Property<string>("InsuranceExpiry")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("insurance_expiry");

                    b.Property<string>("LastMaintenance")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_maintenance");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("model");

                    b.Property<DateOnly?>("NextMaintenance")
                        .HasColumnType("date")
                        .HasColumnName("next_maintenance");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plate_number");

                    b.Property<string>("RegistrationDate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registration_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Year")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("customer_cars");
                });

            modelBuilder.Entity("SwagBackend.Models.CustomerFollow", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("CustomerId", "VendorId");

                    b.HasIndex("VendorId");

                    b.ToTable("customer_follows");
                });

            modelBuilder.Entity("SwagBackend.Models.CustomerInterest", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.HasKey("CustomerId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("customer_interests");
                });

            modelBuilder.Entity("SwagBackend.Models.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("event_types");
                });

            modelBuilder.Entity("SwagBackend.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeepLink")
                        .HasColumnType("text")
                        .HasColumnName("deep_link");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<UserRole>("RecipientType")
                        .HasColumnType("user_role")
                        .HasColumnName("recipient_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<NotificationType>("Type")
                        .HasColumnType("notification_type")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("SwagBackend.Models.OtpVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<OtpPurpose>("Purpose")
                        .HasColumnType("otp_purpose")
                        .HasColumnName("purpose");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("recipient");

                    b.HasKey("Id");

                    b.ToTable("otp_verifications");
                });

            modelBuilder.Entity("SwagBackend.Models.PostCategory", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.HasKey("PostId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("post_categories");
                });

            modelBuilder.Entity("SwagBackend.Models.PostComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment_text");

                    b.Property<Guid>("CommenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("commenter_id");

                    b.Property<UserRole>("CommenterType")
                        .HasColumnType("user_role")
                        .HasColumnName("commenter_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("post_comments");
                });

            modelBuilder.Entity("SwagBackend.Models.PostEventType", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("event_type_id");

                    b.HasKey("PostId", "EventTypeId");

                    b.HasIndex("EventTypeId");

                    b.ToTable("post_event_types");
                });

            modelBuilder.Entity("SwagBackend.Models.PostLike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LikerId")
                        .HasColumnType("uuid")
                        .HasColumnName("liker_id");

                    b.Property<UserRole>("LikerType")
                        .HasColumnType("user_role")
                        .HasColumnName("liker_type");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.HasKey("Id");

                    b.HasIndex("PostId", "LikerId", "LikerType")
                        .IsUnique();

                    b.ToTable("post_likes");
                });

            modelBuilder.Entity("SwagBackend.Models.PostSave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<Guid>("SaverId")
                        .HasColumnType("uuid")
                        .HasColumnName("saver_id");

                    b.Property<UserRole>("SaverType")
                        .HasColumnType("user_role")
                        .HasColumnName("saver_type");

                    b.HasKey("Id");

                    b.HasIndex("PostId", "SaverId", "SaverType")
                        .IsUnique();

                    b.ToTable("post_saves");
                });

            modelBuilder.Entity("SwagBackend.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VendorId", "CustomerId")
                        .IsUnique();

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("SwagBackend.Models.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BannerImage")
                        .HasColumnType("text")
                        .HasColumnName("banner_image");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CommercialRegNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("commercial_reg_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("boolean")
                        .HasColumnName("dark_mode");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<decimal?>("LocationLat")
                        .HasColumnType("numeric")
                        .HasColumnName("location_lat");

                    b.Property<decimal?>("LocationLng")
                        .HasColumnType("numeric")
                        .HasColumnName("location_lng");

                    b.Property<string>("LocationUrl")
                        .HasColumnType("text")
                        .HasColumnName("location_url");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text")
                        .HasColumnName("profile_image");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("push_notifications");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("shop_name");

                    b.Property<string>("ShopType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("shop_type");

                    b.Property<VendorStatus>("Status")
                        .HasColumnType("vendor_status")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("vendors");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorApprovalLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<VendorStatus>("Action")
                        .HasColumnType("vendor_status")
                        .HasColumnName("action");

                    b.Property<DateTime>("ActionedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actioned_at");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("VendorId");

                    b.ToTable("vendor_approval_log");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorCategoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("section_id");

                    b.HasKey("Id");

                    b.HasIndex("SectionId", "Name")
                        .IsUnique();

                    b.ToTable("vendor_category_items");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorCategorySection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("vendor_category_sections");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("vendor_collections");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorCollectionPost", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.HasKey("CollectionId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("vendor_collection_posts");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IdBackFile")
                        .HasColumnType("text")
                        .HasColumnName("id_back_file");

                    b.Property<string>("IdFrontFile")
                        .HasColumnType("text")
                        .HasColumnName("id_front_file");

                    b.Property<string>("LicenseFile")
                        .HasColumnType("text")
                        .HasColumnName("license_file");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("VendorId")
                        .IsUnique();

                    b.ToTable("vendor_documents");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorFollow", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid")
                        .HasColumnName("follower_id");

                    b.Property<Guid>("FollowingId")
                        .HasColumnType("uuid")
                        .HasColumnName("following_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("FollowerId", "FollowingId");

                    b.HasIndex("FollowingId");

                    b.ToTable("vendor_follows");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EventDate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_date");

                    b.Property<string>("EventEndTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_end_time");

                    b.Property<string>("EventTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_time");

                    b.Property<string>("EventTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_title");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<int?>("MediaHeight")
                        .HasColumnType("integer")
                        .HasColumnName("media_height");

                    b.Property<MediaType>("MediaType")
                        .HasColumnType("media_type")
                        .HasColumnName("media_type");

                    b.Property<int?>("MediaWidth")
                        .HasColumnType("integer")
                        .HasColumnName("media_width");

                    b.Property<string>("PostImage")
                        .HasColumnType("text")
                        .HasColumnName("post_image");

                    b.Property<PostType>("Type")
                        .HasColumnType("post_type")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("vendor_posts");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorProfileDetail", b =>
                {
                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("close_time");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("text")
                        .HasColumnName("instagram_url");

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("open_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("whatsapp");

                    b.HasKey("VendorId");

                    b.ToTable("vendor_profile_details");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorSelectedCategory", b =>
                {
                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.HasKey("VendorId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("vendor_selected_categories");
                });

            modelBuilder.Entity("SwagBackend.Models.CarMaintenanceRecord", b =>
                {
                    b.HasOne("SwagBackend.Models.CustomerCar", "Car")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("SwagBackend.Models.ChatMessage", b =>
                {
                    b.HasOne("SwagBackend.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("SwagBackend.Models.CustomerCar", b =>
                {
                    b.HasOne("SwagBackend.Models.Customer", "Customer")
                        .WithMany("Cars")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SwagBackend.Models.CustomerFollow", b =>
                {
                    b.HasOne("SwagBackend.Models.Customer", "Customer")
                        .WithMany("Following")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwagBackend.Models.Vendor", "Vendor")
                        .WithMany("Followers")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("SwagBackend.Models.CustomerInterest", b =>
                {
                    b.HasOne("SwagBackend.Models.Customer", "Customer")
                        .WithMany("Interests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwagBackend.Models.VendorCategoryItem", "Item")
                        .WithMany("CustomerInterests")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("SwagBackend.Models.PostCategory", b =>
                {
                    b.HasOne("SwagBackend.Models.VendorCategoryItem", "Item")
                        .WithMany("PostCategories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwagBackend.Models.VendorPost", "Post")
                        .WithMany("Categories")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SwagBackend.Models.PostComment", b =>
                {
                    b.HasOne("SwagBackend.Models.VendorPost", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SwagBackend.Models.PostEventType", b =>
                {
                    b.HasOne("SwagBackend.Models.EventType", "EventType")
                        .WithMany("PostEventTypes")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwagBackend.Models.VendorPost", "Post")
                        .WithMany("EventTypes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SwagBackend.Models.PostLike", b =>
                {
                    b.HasOne("SwagBackend.Models.VendorPost", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SwagBackend.Models.PostSave", b =>
                {
                    b.HasOne("SwagBackend.Models.VendorPost", "Post")
                        .WithMany("Saves")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SwagBackend.Models.Review", b =>
                {
                    b.HasOne("SwagBackend.Models.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwagBackend.Models.Vendor", "Vendor")
                        .WithMany("Reviews")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorApprovalLog", b =>
                {
                    b.HasOne("SwagBackend.Models.Admin", "Admin")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwagBackend.Models.Vendor", "Vendor")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorCategoryItem", b =>
                {
                    b.HasOne("SwagBackend.Models.VendorCategorySection", "Section")
                        .WithMany("Items")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorCollection", b =>
                {
                    b.HasOne("SwagBackend.Models.Vendor", "Vendor")
                        .WithMany("Collections")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorCollectionPost", b =>
                {
                    b.HasOne("SwagBackend.Models.VendorCollection", "Collection")
                        .WithMany("Posts")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwagBackend.Models.VendorPost", "Post")
                        .WithMany("CollectionPosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorDocument", b =>
                {
                    b.HasOne("SwagBackend.Models.Vendor", "Vendor")
                        .WithOne("Document")
                        .HasForeignKey("SwagBackend.Models.VendorDocument", "VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorFollow", b =>
                {
                    b.HasOne("SwagBackend.Models.Vendor", "Follower")
                        .WithMany("VendorFollowing")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwagBackend.Models.Vendor", "Following")
                        .WithMany("VendorFollowers")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorPost", b =>
                {
                    b.HasOne("SwagBackend.Models.Vendor", "Vendor")
                        .WithMany("Posts")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorProfileDetail", b =>
                {
                    b.HasOne("SwagBackend.Models.Vendor", "Vendor")
                        .WithOne("ProfileDetail")
                        .HasForeignKey("SwagBackend.Models.VendorProfileDetail", "VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorSelectedCategory", b =>
                {
                    b.HasOne("SwagBackend.Models.VendorCategoryItem", "Item")
                        .WithMany("VendorSelections")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwagBackend.Models.Vendor", "Vendor")
                        .WithMany("SelectedCategories")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("SwagBackend.Models.Admin", b =>
                {
                    b.Navigation("ApprovalLogs");
                });

            modelBuilder.Entity("SwagBackend.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SwagBackend.Models.Customer", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Following");

                    b.Navigation("Interests");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SwagBackend.Models.CustomerCar", b =>
                {
                    b.Navigation("MaintenanceRecords");
                });

            modelBuilder.Entity("SwagBackend.Models.EventType", b =>
                {
                    b.Navigation("PostEventTypes");
                });

            modelBuilder.Entity("SwagBackend.Models.Vendor", b =>
                {
                    b.Navigation("ApprovalLogs");

                    b.Navigation("Collections");

                    b.Navigation("Document");

                    b.Navigation("Followers");

                    b.Navigation("Posts");

                    b.Navigation("ProfileDetail");

                    b.Navigation("Reviews");

                    b.Navigation("SelectedCategories");

                    b.Navigation("VendorFollowers");

                    b.Navigation("VendorFollowing");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorCategoryItem", b =>
                {
                    b.Navigation("CustomerInterests");

                    b.Navigation("PostCategories");

                    b.Navigation("VendorSelections");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorCategorySection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorCollection", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("SwagBackend.Models.VendorPost", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("CollectionPosts");

                    b.Navigation("Comments");

                    b.Navigation("EventTypes");

                    b.Navigation("Likes");

                    b.Navigation("Saves");
                });
#pragma warning restore 612, 618
        }
    }
}
